### ISSUE TITLE
Brightness control failure

### ISSUE THREAD

**Issue by liangtb** [mayankk2308/purge-nvda#1]
exe script and reboot, the lightness adjustment of the internal screen is out of function….

**Comment by mayankk2308** [comment]
This may be because of the direct wiring of the display through the discrete chip. A solution may not be possible. Using the script also disables HDMI and Thunderbolt ports for video output (excluding external graphics).

**Comment by liangtb** [comment]
I can use app to achieving the adjustment with brightness slider.

**Comment by mayankk2308** [comment]
What app are you referring to?

**Comment by liangtb** [comment]
brightness slider.

**Comment by mayankk2308** [comment]
More precisely, I assume you mean from **Settings > Displays > Brightness Slider** and not a third-party application yes? If that is true, it is interesting to see that disabling the discrete graphics drivers can impact keyboard setting changes. Are you able to adjust keyboard brightness, out of curiosity?

**Comment by liangtb** [comment]
The Settings > Displays > Brightness and button of keyboard is non-function with this script, I use the app named brightness slider to control the lightness by software, but the power consumption of screen is always same as the default lightness of displays.

**Comment by liangtb** [comment]
It's a temp solution but a general one...

**Comment by mayankk2308** [comment]
Oh, my bad for not understanding that it was the name of the app ;p. I think that's the only solution. Maybe I could include such a capability in a future release haha ;p - currently closing this issue. Many thanks for bringing it up!

**Comment by mayankk2308** [comment]
Please try the latest release and let me know if you have this issue.

**Comment by tnboman** [comment]
Hi - I'm having the same issue, although it's marked as fixed? I'm running Mojave, lastest version of both purge-wrangler and purge-nvda. The brightness control media keys do nothing and the brightness slider in the display settings under system settings panel are not shown.

I have the MBP Retina late 2014 with Nvidia GT 750M and built in Intel Iris Pro. Running a RX Vega 64 via a Sonnet 650W Breakaway Box.

Any ideas?

**Comment by mayankk2308** [comment]
It is a known issue. If you’re not using external display, you don’t need this patch, which would restore your brightness control. Read my first post in this thread as to why this is a problem.

**Comment by tnboman** [comment]
Ah, sorry I should have read the thread closer. Thanks for developing these great patches – it's great to be able to run the eGPU through TB2 at all, so thank you.

**Comment by mayankk2308** [comment]
@tnboman You are most welcome! I actually don't even have the 750M model (which I did previously) anymore, which makes it difficult to develop this script further.
