### ISSUE TITLE
Brightness doesn't work on 2014 15' Macbook Pro Mojave and 3.0.1

### ISSUE THREAD

**Issue by felixbinder** [mayankk2308/purge-nvda#10]
When the AMD fix is enabled, I can't change the brightness of the internal display. The brightness slider disappers from settings, too. Uninstalling allows me to change the brightness again.

What works is disabling the backlight with ctrl+shift+power key.

This happens on macOS 10.14.1 (18B75), on a MacBookPro11,3 with PrugeNVDA (3.0.1) with a Radeon RX 580 in an Akitio Node Pro. Let me know if there's something I can do to help!

**Comment by mayankk2308** [comment]
This is an inherent limitation/side effect of the patch, unfortunately. I shall update the documentation to include all known issues soon.
