### ISSUE TITLE
I can not enter the script menu

### ISSUE THREAD

**Issue by funk4d** [mayankk2308/purge-nvda#11]
I can not restore the factory settings after turning off the NVIDIA video card. I'm getting this message
`This script only supports macs with discrete NVIDIA GPUs.`

**Comment by mayankk2308** [comment]
Alternative way to uninstall is to reset NVRAM and reboot twice.

Thank you for reporting this. I shall look into it shortly.

**Comment by mayankk2308** [comment]
**3.0.2** removes dGPU verification. A better system will be implemented at a later date. I do not have access to an applicable Mac, making development of this script rather difficult as I cannot test it.
