### ISSUE TITLE
Question on how Suppress NVIDIA GPUs works

### ISSUE THREAD

**Issue by NaanProphet** [mayankk2308/purge-nvda#15]
Hi there! Love your work.

I was wondering how option 5, Suppress NVIDIA GPUs is supposed to work. I saw in the source code it turns off automatic graphic switching `agc=-1` and sets the NVRAM to prefer the integrated graphics card `IG_POWER_PREF="%01%00%00%00"`.

I have option 5 enabled and curiously (to my surprise) the NVIDIA internal dGPU is still working during playback in Final Cut Pro X.

![Screen Shot 2020-05-28 at 8 42 22 AM](https://user-images.githubusercontent.com/2568736/83143089-6ca26080-a0bf-11ea-84e2-ffb16bd3b93c.png)

![Screen Shot 2020-05-28 at 8 45 34 AM](https://user-images.githubusercontent.com/2568736/83143231-9eb3c280-a0bf-11ea-834d-f92bb189a8e0.png)

My machine specs are:

* MacBookPro9,1 (15-inch, Mid 2012)
* Mac OS X 10.14.6 Mojave (fresh re-install)
* NVIDIA GeForce GT 650M 1 GB
* Final Cut Pro X 10.4.8

Can certain applications, like Final Cut, essentially bypass the setting and access the dGPU?

**Comment by mayankk2308** [comment]
@NaanProphet this looks like a case where the mux did not switch. If the mux correctly remains fixed onto iGPU, then FCPX should be unable to use the dGPU. Retry patching.

**Comment by NaanProphet** [comment]
Retrying the patching (option 5) results in the same behavior in FCP X.

**Comment by mayankk2308** [comment]
Can you check if while using the suppress configuration, the dGPU is available as a compute GPU in benchmarks like Geekbench? If so, this is likely because I am not ‘disabling’ the NVIDIA GPU drivers (otherwise it runs hotter).
