### ISSUE TITLE
Will this work for internal NVIDIA GPUs in MP 7,1?

### ISSUE THREAD

**Issue by alphanull** [mayankk2308/purge-nvda#17]
Just stumbled over this project while searching for a solution with the new NVIDIA Ampere Cards (i.e. 3080s and 3090s) in the Mac Pro 2019. Most of these - but apparently not all models - have problems with sleep in macOS, i.e. the OS crashes when going into sleep or waking up.

Any idea if this script also might help in this case, or - if not - any ideas how to make macOS ignore the NVIDIA card, and/or do some patches so that sleep does work with such a card? Of course we are aware that those cards are not supported with macOS, but they are usable with bootcamp. Still, not being able to sleep with such a card under macOS is a dealbreaker for many of us, so any insights are greatly appreciated!

**Comment by mayankk2308** [comment]
Unfortunately this project won't be helpful in your case. Regarding Mac Pro 7,1 though, Apple mentions something about NVIDIA GPUs for use in Windows here: https://support.apple.com/en-us/HT210408

The recommendation is not to use Slot #2 for this. Perhaps that may be the cause of your issues?
