### ISSUE TITLE
Issue with sleep, logout + clamshell sleep = shutdown

### ISSUE THREAD

**Issue by liangtb** [mayankk2308/purge-nvda#3]
I test three ways, as follows

1) directly cover, will not sleep display and macos, consuming the power
2) lock and cover, will not sleep display and macos, consuming the power
3) log out and cover, after a short time, it's okay, but even a bit longer time, it will be shut down incidentally
In conclusion, at current this script will disable the normal function of sleeping macbook.

**Comment by mayankk2308** [comment]
This is interesting. I do have a B4 installation to test with - just not enough free time.

**Comment by mayankk2308** [comment]
I suspect these issues will be resolved if you use the latest release. Please provide an update once you do try.

**Comment by mayankk2308** [comment]
I am encountering some of these issues on **macOS 10.13.4** still.

**Comment by kecinzer** [comment]
I'm trying this script on 10.12.6 and it looks like MB sleeps normaly.

**Comment by mayankk2308** [comment]
**@kecinzer** what version of the script are you using? Also are you using an option or running it without arguments?

**Comment by mayankk2308** [comment]
Issue not affecting **macOS Sierra**, and is only applicable to **High Sierra**.

**Comment by mayankk2308** [comment]
This does not seem it can be resolved on my part, nor will I put in the effort to try since Apple changed something in High Sierra causing this.
