### ISSUE TITLE
10.13 B4 and 10.13 Public drivers almost similar

### ISSUE THREAD

**Issue by liangtb** [mayankk2308/purge-nvda#4]
I compared the two driver and found almost same document, is there some difference in other folders conducting the abnormal boot in 10.13 with the script?

**Comment by mayankk2308** [comment]
Issue is not as straightforward as it seems, and drivers are not exactly the cause since they can be replaced (Beta 4 drivers boot on public build). Probably the lower level APIs that handle GFX. Could you try switching to NVIDIA Web Drivers and plugging in eGPU?

**Comment by liangtb** [comment]
Okay, I have 10.13 and 10.13beta4, web drivers should only support 10.13 official, Do I test it in 10.13?

**Comment by mayankk2308** [comment]
10.13 (17A405)

**Comment by liangtb** [comment]
10.13 (17A405) with  378.10.10.10.15.117, I just got black  and frozen screen, must reboot, totally incompatible, even no pop out eGPU notification.
I tried twice as the same result.

**Comment by mayankk2308** [comment]
Ok thanks for testing.

**Comment by liangtb** [comment]
May the owner of Nvidia web driver can solve this problem, when no eGPU, enable nGPU, when plug eGPU, disable nGPU, if this, it perfectly.

**Comment by mayankk2308** [comment]
NVIDIA creates the web drivers, so its really up to them.

**Comment by liangtb** [comment]
web driver just modify geforce driver, no nvda.

**Comment by mayankk2308** [comment]
NVIDIA does: http://www.nvidia.com/download/driverResults.aspx/125379/en-us

**Comment by liangtb** [comment]
Nvidia totally disregard the apple eGPU with web driver, a brilliant way...they have techs to modify it for eGPU, but I guess they won't out of the benefit.

**Comment by liangtb** [comment]
ver.117 has a key diff with ver.114, no NVDAstatupweb.kext.  Apple take over privilege of the nvda boot totally, see the blog http://www.macvidcards.com/blog/high-sierra-supplemental-update-hold-off-for-now-if-you-need-web-driver

**Comment by mayankk2308** [comment]
Using **Beta 4** AppleACPIPlatform.kext in the newer build results in complete boot failure. Quite interestingly, this is the kext that references the device drivers for the devices on the PCIe lane. I'm guessing it could not do so because the references (on the new build) were different. I would imagine that a set of kernel extensions that would allow **AppleACPIPlatform** from Beta 4 to work on the new build could potentially be a solution (a rather ugly one I must say).

Also, **NVDAStartupWeb.kext** is present in the new version, but Apple's own startup kext loads alongside.

**Comment by liangtb** [comment]
Extension folder hasn't added more new files about boot or gpu or etc... maybe modify in some documents. The number of files in Extension is almost same between 10.13 and 10.13beta4.

**Comment by liangtb** [comment]
<img width="1069" alt="acpi" src="https://user-images.githubusercontent.com/8098980/31314096-1e4527d8-ac2a-11e7-80aa-df6337ff2780.png">
the  AppleACPIPlatform is same, just ver. a little diff

**Comment by liangtb** [comment]
So what Apple do something change this situation? A SMART Apple and Nvidia, Play consumers in their palms.

**Comment by liangtb** [comment]
You using the older replace the new one, it failed, just because some ver. diff, so these ver. must affect other documents in some ways. It's complicated for everyone except Apple.

**Comment by liangtb** [comment]
The info of web driver is almost as same as originated one, the exe packaging must be different, but consider these binary-code, I think these ways are blocked, unless Apple or Nvidia provides supports for eGPU, 10.13beta4 is the last high sierra ver which support eGPU for AMD.
This's  a exemplary example that company never honestly  think about their consumers, just for money. For me, ultimate way is to change the computer to AMD-based.

**Comment by mayankk2308** [comment]
Please try the latest release of the script.

**Comment by mayankk2308** [comment]
Resolved on **macOS 10.13.4 B1**.
