### ISSUE TITLE
Safe-boot compatible with AMD-eGPU

### ISSUE THREAD

**Issue by liangtb** [mayankk2308/purge-nvda#6]
Both Nvidia web driver and Apple official driver are compatible with eGPU-sapphire-RX580.
In safe boot, Luxmark no display supported OpenCL cards that iGPU, nGPU, eGPU, but with DP(mdp) output signal of Macbook's nGPU and eGPU's RX580, external **screen** work fine, so nGPU and eGPU are both activated in safe boot.
Diff: loaded different kexts.
[kext.zip](https://github.com/mayankk2308/purge-nvda/files/1368884/kext.zip)

**Comment by liangtb** [comment]
diff kext which normal boot add:

com.apple.driver.AppleThunderboltDPOutAdapter
com.apple.driver.AppleThunderboltEDMSink
com.apple.driver.AppleThunderboltIP
com.apple.driver.AppleFIVRDriver
com.apple.vecLib.kext
com.apple.iokit.IOAudioFamily
com.apple.iokit.IOHDAFamily
com.apple.driver.AppleHDAController
com.apple.driver.AppleCameraInterface
com.apple.AVEBridge
com.intel.driver.EnergyDriver
com.apple.driver.AppleIntelHD5000Graphics
com.apple.driver.eficheck
com.apple.driver.pmtelemetry
com.apple.driver.AppleSSE
com.apple.iokit.IOUserEthernet
com.apple.driver.AppleHV
com.apple.iokit.IOTimeSyncFamily
com.apple.AGDCPluginDisplayMetrics
com.apple.driver.AppleUpstreamUserClient
com.apple.driver.AudioAUUC
com.apple.kext.OSvKernDSPLib
com.apple.driver.DspFuncLib
com.apple.driver.AppleHDA
com.apple.driver.AppleHDAHardwareConfigDriver
com.apple.iokit.IOSerialFamily
com.apple.iokit.IOBluetoothSerialManager
com.apple.driver.ApplePlatformEnabler
com.apple.GeForce
com.apple.filesystems.smbfs

**Comment by mayankk2308** [comment]
Please try this:
`sudo mv /System/Library/Extensions/GeForce*.* /Users/<your_username>/Desktop/`

Then run the script in **nvram-only** mode on **17A405** and reboot. Of course, don't use the script and ensure SIP is disabled. Then test eGPU.

**Comment by liangtb** [comment]
I tried, it’s not working, besides, the gt750m can’t output signal to external screen, it’s different with safe boot which gt750m can output signal to external screen.

**Comment by mayankk2308** [comment]
Can you try the latest script? At least it boots High Sierra iGPU only. 

If eGPU does not work, could you try moving the ThunderboltDPOut kext and then running the script?

**Comment by liangtb** [comment]
yes, it can iGPU boot, but I guess this non-related with Extensions folder, I am wrong?

**Comment by mayankk2308** [comment]
It is related. If I don’t move the appropriate kexts, iGPU boot will not be persistent.

**Comment by liangtb** [comment]
mv /System/Library/Extensions/GeForce*.* "$backup_dir", it's same as before....., just leave NVDA*.kexts

**Comment by mayankk2308** [comment]
Yes, just moving the GeForce kexts ensures iGPU persistent boots, contrary to the methods used for AMD, where the drivers were indeed moved. This is a new discovery.

**Comment by liangtb** [comment]
but in safe boot without geforce*.kexts, gt750m can actually output signal to external screen, but in normal boot with purge-nvda 1.2.1, it did't happen. That's the point why lead gt750m output signal without geforce*.kext

**Comment by mayankk2308** [comment]
I see what you mean. Thing is though, in Safe Boot there is no acceleration. So I want to know what exactly is driving the display. Perhaps EFI.

**Comment by liangtb** [comment]
In safe boot, Macbook don't have eficheck.kext. This is only diff about efi.

**Comment by mayankk2308** [comment]
Well, maybe we have to completely prevent the NVIDIA from being able to output to the display, because that's how the hack worked on B4 yes? So if we can simulate the same thing, we could probably have working external GPUs.

**Comment by mayankk2308** [comment]
I just made a commit. Could you clone my repo and use the latest script? You can keep pulling changes and test as I make changes. For now, just removed DisplayPort support (boots fine). Want to test with eGPU. Could you please try?

**Comment by liangtb** [comment]
okay, I will try now

PS:dp is disabled  in both Macbook and RX580, even no output signal.

**Comment by mayankk2308** [comment]
Ok thanks..

**Comment by liangtb** [comment]
**Libm.kext** is the key to solve Nvidia-based Macbook compatible with AMD-eGPU.

**Libm.kext** contains a bunch of compatibility checks such as  **AppleKernelExternalComponent.**

**Comment by mayankk2308** [comment]
Not sure that that's related to external graphics.

**Comment by mayankk2308** [comment]
Also, quick question, does the updated script accelerate the display on Beta 4? If the issue really is with DP outputs, it should not be able to work. Could you try the updated script on Beta 4 (uninstall any previous changes).

Also try booting in 10.13 recovery (not the beta) with external graphics connected. Recovery does not include all the kexts an ordinary macOS install does, but the display is accelerated.

**Comment by liangtb** [comment]
Recovery is okay, I tested. I will test it on Beta4 with your new script after I watched the new big bang for 20mins.

**Comment by liangtb** [comment]
Should I establishing a telegram group for communicating, which is so efficient than forum, we can both use telegram and forum.

**Comment by liangtb** [comment]
It did't work on beta4, no dp output signal to external screen.


On 10 October 2017 at 2:57:04 PM, Mayank Kumar (notifications@github.com)
wrote:

Also, quick question, does the updated script accelerate the display on
Beta 4? If the issue really is with DP outputs, it should not be able to
work. Could you try the updated script on Beta 4 (uninstall any previous
changes).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mayankk2308/purge-nvda/issues/6#issuecomment-335378971>,
or mute the thread

**Comment by mayankk2308** [comment]
That’s what I expected. Hmm. Recovery was able to accelerate the eGPU + display, right? So we should compare recovery loaded kexts versus main disk boot.

**Comment by liangtb** [comment]
10.13beta4 will fail-boot at a certain level with the latest script.

**Comment by liangtb** [comment]
Recovery mode is okay natively, but 10.13beta4 will fail-boot at a certain level with the latest script.

**Besides,** Did you add enable SIP in your script? every time I uninstall script, SIP is set to enabled, I must reboot again to disable SIP, several APPS rely on disabled SIP....

_Can you remove enable SIP or add extra ver. of script without enable SIP?_

**Comment by mayankk2308** [comment]
What do you mean “at a certain level”? Irrespective of that, my primary concern is the public build. The old versions of the script will be available anyway for those concerned. 

Also, the script doesn’t manage SIP. I have continuously used it (install + uninstall for testing) without SIP modifications.

**Comment by liangtb** [comment]
My config of 10.13beta4 is located in a portable ssd drive. Every time I use latest script with installment or uninstallation, uninstallation always triggered to enable SIP. Besides, only first time after install the latest script, can boot successfully.
My  portable ssd drive is APFS volume, I don't know whether is the problem, besides before this, my  portable ssd drive is HFS+ volume, using prior scripts just fine.
After I uninstalled the latest script in recovery mode, boot successfully again...

**Comment by liangtb** [comment]
Are you willing to represent me to call Apple executive liaison about Nvidia-based device malfunction?
Because I'm in China, my mail is ltingbiao@gmail.com, if you will, mail me and I re-transmit mail to you.

**Comment by mayankk2308** [comment]
If you boot into another installation of macOS that has not had **purge-nvda** run, the NVRAM changes are undone. So if you keep booting into 10.13 (after running the script), it will boot in iGPU mode only.
Not sure about your issue with SIP. Cannot reproduce. Try resetting PRAM using the keyboard shortcut on boot. Then turn off SIP and use the script.

Apple does not officially support external graphics on Thunderbolt 2. I don't exactly know what you mean by "represent you", but I don't see any reason for Apple to look into this issue (which is already classified as an **unsupported configuration**). While it would be awesome for them to fix it, we should also keep in mind that officially, eGPU support has yet to come (Spring 2018). Developer Relations has also confirmed (via my bug reports) that they would look into iGPU-only boot options as well as making the Mac firmware more flexible.

**Comment by liangtb** [comment]
Not officially support does not mean that they can just ignore this, IF
only support for TB3, I can accept, But even before 2012 devices just only
iGPU then can be applied, this is non-sense. When I mail to cook, I
explicitly address this, This situation happened just because the bad
relation between Nvidia and Apple, even step. Apple does not intent to
solve this intentionally.


On 11 October 2017 at 2:15:01 AM, Mayank Kumar (notifications@github.com)
wrote:

If you boot into another installation of macOS that has not had *purge-nvda*
run, the NVRAM changes are undone. So if you keep booting into 10.13 (after
running the script), it will boot in iGPU mode only.
Not sure about your issue with SIP. Cannot reproduce. Try resetting PRAM
using the keyboard shortcut on boot. Then turn off SIP and use the script.

Apple does not officially support external graphics on Thunderbolt 2. I
don't exactly know what you mean by "represent you", but I don't see any
reason for Apple to look into this issue (which is already classified
as an *unsupported
configuration*). While it would be awesome for them to fix it, we should
also keep in mind that officially, eGPU support has yet to come (Spring
2018). Developer Relations has also confirmed (via my bug reports) that
they would look into iGPU-only boot options as well as making the Mac
firmware more flexible.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mayankk2308/purge-nvda/issues/6#issuecomment-335561430>,
or mute the thread

**Comment by mayankk2308** [comment]
I see what you mean friend. Let's hope that things work out.

**Comment by mayankk2308** [comment]
**@liangtb** with **v1.2.1** of the script (not the latest commit), have you tried booting with the eGPU plugged in instead of hotplugging? Could you try and provide an update?

**Comment by liangtb** [comment]
yes, I tried ,same issue.

**Comment by mayankk2308** [comment]
Resolved on **macOS 10.13.4 B1**.
