### ISSUE TITLE
Only black screens after purged NVIDIA dGPU

### ISSUE THREAD

**Issue by r-luo** [mayankk2308/purge-nvda#8]
I'm using a mid-2014 15 inch Macbook pro with NVIDIA dGPU:
![image](https://user-images.githubusercontent.com/3460073/40148170-af6b4608-593a-11e8-8dc8-dc218ca57900.png)
My eGPU setup is HP Omen Accelerator + AMD RX 580, connected with TB3 + TB3 -> TB2 converter.

I installed purge-wrangler, and then used purge-nvda to install NVIDIA suppression. Whenever I connect to the eGPU, all my external monitors would power up but stay dark; and the system would freeze (can only move cursor)... I've tried the methods detailed on https://egpu.io/forums/mac-setup/script-enable-egpu-on-tb1-2-macs-on-macos-10-13-4/paged/1/ but had no luck (the macbook freezes after hot plugging eGPU and I am not able to log out at all 😕).

**Comment by r-luo** [comment]
Never mind, enable AMD eGPU didn't work for me the first time, so I tried suppress NVIDIA dGUP and it still didn't work, so I uninstalled the system and retried enabling AMD eGPU and it worked 😄

**Comment by julientom** [comment]
Hello r-Luo

I am having the exact same problem you had last year - on the almost same configuration 

I have a late 2013 mbp with Intel Iris and NVIDIA GeForce GT 750M.
Mac OSx Mojave 10.14.1

I can enjoy the power of computing 7 Times faster thanks to my Sapphire Nitro+ Vega 56 but I cannot use external display through this new eGPU ( of course with tb2/tb3 adaptor).
A/ I did use purge-wrangler -> it works well but only black screen on my external Display of the eGPU. 
B/ Then I tried Purge-NVDA, I trid all kind of option and combination ( option 1  / option  1+ option 2 - option  1+option 4 - or option 3 only....)  but I just cannot boot anymore... or have black screen...

So when you said "uninstalled the system"  and retried enabling AMD eGPU... What exactly did you do please ( step by step please ) ?
Do you still use this set up with Mojave ?

Thanks a million time for your help

Julien

**Comment by mayankk2308** [comment]
https://egpu.io/forums/mac-setup/nvidia-workaround-for-high-sierra-egpu-acceleration/

For details. It is mentioned that this may leave the system unbootable because the mux may not change.
