### ISSUE TITLE
MacBook Pro 15 retina 2012 with bad NV graphics

### ISSUE THREAD

**Issue by Rino63** [mayankk2308/purge-nvda#9]
I have MacBook MacBook Pro 15 retina 2012 with bad working NV graphics.
All solutions for removing Nvidia drivers do not allow using only integrated graphics with a working sleep and a dimmer control. When removing the Nvidia drivers and using this script (https://github.com/0xbb/gpu-switch), at the start of the system, you can use the laptop fully. Adjust the backlight and sleep work. But the script does not work on macOS 10.12.4+.
Please tell me, does your program allow me to use only integrated graphics when starting my laptop without NVidia drivers?

**Comment by mayankk2308** [comment]
The primary purpose of this script was to enable AMD eGPU video acceleration and provide workarounds for bad GPUs (as I cannot test). The iGPU mux setting technically uses only integrated graphics when booting the laptop.
